name: Push Source

on:
  workflow_dispatch:

jobs:
  push-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: clone source
        run: wget "source url"

      - name: unzip
        run: unzip "zipfile".zip
       
      - name: Commit and push
        run: |
          git config --local user.name "abhiram79"
          git config --local user.email "email"
          git add .
          git commit -m "commit message"
          git push origin main
